const $=id=>document.getElementById(id);let ctx,stream,source,gain,analyser,osc,oscGain,delay,filter,dist,mute=false;const effect=$("effect"),pitch=$("pitch"),amount=$("amount"),pitchOut=$("pitchOut"),amountOut=$("amountOut"),fill=$("meterFill"),meterText=$("meterText"),status=$("status"),wave=$("waveform"),waveCtx=wave?.getContext('2d');
function curve(a){const n=44100,c=new Float32Array(n);for(let i=0;i<n;i++){const x=i*2/n-1;c[i]=(3+a)*x*20*Math.PI/180/(Math.PI+a*Math.abs(x))}return c}
function setup(){ctx=new(window.AudioContext||window.webkitAudioContext)();source=ctx.createMediaStreamSource(stream);gain=ctx.createGain();analyser=ctx.createAnalyser();analyser.fftSize=1024;filter=ctx.createBiquadFilter();dist=ctx.createWaveShaper();dist.curve=curve(8);dist.oversample='4x';delay=ctx.createDelay(.5);delay.delayTime.value=.08;osc=ctx.createOscillator();osc.frequency.value=30;oscGain=ctx.createGain();oscGain.gain.value=0;source.connect(filter).connect(dist).connect(delay).connect(gain).connect(analyser).connect(ctx.destination);osc.connect(oscGain).connect(gain);osc.start();apply();loop()}
function apply(){if(!ctx)return;const e=effect.value,a=+amount.value/100,s=+pitch.value;pitchOut.value=`${s>0?'+':''}${s} st`;amountOut.value=`${Math.round(a*100)}%`;filter.type='peaking';filter.frequency.value=1800;filter.Q.value=.7;filter.gain.value=0;dist.curve=curve(4+16*a);delay.delayTime.value=.04+.16*a;oscGain.gain.value=0;if(e==='deep'){filter.type='lowshelf';filter.frequency.value=500;filter.gain.value=12*a}if(e==='high'){filter.type='highshelf';filter.frequency.value=1400;filter.gain.value=12*a}if(e==='radio'){filter.type='bandpass';filter.frequency.value=1800;filter.Q.value=1.2;dist.curve=curve(15)}if(e==='robot'){oscGain.gain.value=.18*a;osc.frequency.value=55+90*a}if(e==='alien'){oscGain.gain.value=.12*a;osc.frequency.value=25+55*a;delay.delayTime.value=.18}}
async function start(){try{stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});setup();status.textContent='LIVE';$('start').disabled=true;$('stop').disabled=false;$('mute').disabled=false}catch(e){status.textContent='MIC BLOCKED';alert('Microphone access failed. Allow the site to use your microphone, then try again.')}}
function stop(){if(!stream)return;stream.getTracks().forEach(t=>t.stop());ctx?.close();ctx=null;stream=null;status.textContent='OFFLINE';$('start').disabled=false;$('stop').disabled=true;$('mute').disabled=true;fill.style.width='0%';meterText.textContent='Mic level: 0%';drawWave([])}
$('mute').onclick=()=>{mute=!mute;gain.gain.value=mute?0:1;$('mute').textContent=mute?'🔊 Unmute':'🔇 Mute'};$('start').onclick=start;$('stop').onclick=stop;effect.oninput=apply;pitch.oninput=apply;amount.oninput=apply;
function drawWave(d){if(!waveCtx||!wave)return;const w=wave.width=wave.clientWidth*devicePixelRatio,h=wave.height=wave.clientHeight*devicePixelRatio;waveCtx.clearRect(0,0,w,h);waveCtx.beginPath();waveCtx.lineWidth=2*devicePixelRatio;waveCtx.strokeStyle='#c77dff';const mid=h/2;for(let i=0;i<d.length;i++){const x=i*w/(d.length-1),y=mid+d[i]/128*mid*.85;i?waveCtx.lineTo(x,y):waveCtx.moveTo(x,y)}waveCtx.stroke()}
function loop(){if(!analyser)return;const d=new Uint8Array(analyser.fftSize);analyser.getByteTimeDomainData(d);let sum=0;for(const x of d){const v=(x-128)/128;sum+=v*v}const level=Math.min(100,Math.sqrt(sum/d.length)*180);fill.style.width=level+'%';meterText.textContent=`Mic level: ${Math.round(level)}%`;drawWave(d);requestAnimationFrame(loop)}
const tts=$('tts'),ttsText=$('ttsText'),recognize=$('recognize'),transcript=$('transcript'),fillerBlock=$('fillerBlock');tts.onclick=()=>{const text=ttsText.value.trim();if(!text)return;if(!('speechSynthesis'in window)){alert('Text-to-speech is not supported in this browser.');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);speechSynthesis.speak(u)};
function cleanFillers(text){if(!fillerBlock?.checked)return text;return text.replace(/(^|\s)(uh+|um+|er+|erm+|hmm+|mm+|like)(?=\s|[,.!?]|$)/gi,'$1').replace(/\s{2,}/g,' ').trim()}
let recognition=null;if('SpeechRecognition'in window||'webkitSpeechRecognition'in window){const R=window.SpeechRecognition||window.webkitSpeechRecognition;recognition=new R();recognition.continuous=true;recognition.interimResults=true;recognition.lang='en-AU';recognition.onresult=e=>{let out='';for(let i=e.resultIndex;i<e.results.length;i++)out+=e.results[i][0].transcript;transcript.textContent=cleanFillers(out)||'Listening…'};recognition.onerror=e=>transcript.textContent='Recognition error: '+e.error;recognition.onend=()=>{recognize.textContent='🎧 Start Recognition';recognize.classList.remove('active')}}recognize.onclick=()=>{if(!recognition){transcript.textContent='Speech recognition is not supported in this browser.';return}if(recognize.classList.contains('active')){recognition.stop();recognize.textContent='🎧 Start Recognition';recognize.classList.remove('active')}else{recognition.start();recognize.textContent='⏹ Stop Recognition';recognize.classList.add('active');transcript.textContent='Listening…'}};window.addEventListener('resize',()=>drawWave([]));